// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/conversation/list": {
            "get": {
                "tags": [
                    "会话模块"
                ],
                "summary": "获取会话列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.ConversationInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/conversation/unreadClear/{peerId}": {
            "post": {
                "tags": [
                    "会话模块"
                ],
                "summary": "清楚当前会话的未读计数",
                "parameters": [
                    {
                        "type": "string",
                        "description": "对方用户ID",
                        "name": "peerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/friend/accept/{friendId}": {
            "post": {
                "tags": [
                    "好友模块"
                ],
                "summary": "同意好友申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "好友ID",
                        "name": "friendId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/friend/add": {
            "post": {
                "tags": [
                    "好友模块"
                ],
                "summary": "添加好友",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FriendReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/friend/list": {
            "get": {
                "tags": [
                    "好友模块"
                ],
                "summary": "获取好友列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.FriendResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/friend/reject/{friendId}": {
            "post": {
                "tags": [
                    "好友模块"
                ],
                "summary": "拒绝好友申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "好友ID",
                        "name": "friendId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/friend/requests": {
            "get": {
                "tags": [
                    "好友模块"
                ],
                "summary": "获取好友请求列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.FriendApplyResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/friend/requests/unread": {
            "get": {
                "tags": [
                    "好友模块"
                ],
                "summary": "获取好友请求未读计数",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "integer",
                                                "format": "int64"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/create": {
            "post": {
                "tags": [
                    "群组模块"
                ],
                "summary": "创建群聊",
                "parameters": [
                    {
                        "description": "创建群参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.EmptyData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/detail/{groupId}": {
            "get": {
                "tags": [
                    "群组模块"
                ],
                "summary": "获取群详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.GroupDetailVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/invite": {
            "post": {
                "tags": [
                    "群组模块"
                ],
                "summary": "邀请加入群",
                "parameters": [
                    {
                        "description": "邀请入群参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.InviteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.EmptyData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/group/members/{groupId}": {
            "get": {
                "tags": [
                    "群组模块"
                ],
                "summary": "获取群详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "群组ID",
                        "name": "groupId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.GroupMemberVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/message/list": {
            "get": {
                "tags": [
                    "消息模块"
                ],
                "summary": "获取消息历史记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "对方用户ID",
                        "name": "peerId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数，默认20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Message"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/upload/img": {
            "post": {
                "description": "上传聊天图片，返回可访问URL",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "文件相关"
                ],
                "summary": "图片文件上传",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件(jpg/png/gif)",
                        "name": "img",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误/文件非法",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/upload/send": {
            "post": {
                "tags": [
                    "聊天模块"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "description": "聊天参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.EmptyData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/delete": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "删除用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.EmptyData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.UserRes"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/list": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.UserRes"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.EmptyData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/update": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "修改用户消息",
                "parameters": [
                    {
                        "description": "修改参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/controller.EmptyData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ws/{token}": {
            "get": {
                "description": "建立 WebSocket 长连接，用于实时聊天",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "聊天模块"
                ],
                "summary": "WebSocket 连接websocket接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户认证token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "WebSocket 连接成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "连接失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.EmptyData": {
            "type": "object"
        },
        "models.ConversationInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastMsg": {
                    "type": "string"
                },
                "lastTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "peerId": {
                    "description": "对方ID",
                    "type": "integer"
                },
                "type": {
                    "description": "0单聊 1群聊",
                    "type": "integer"
                },
                "unreadCount": {
                    "type": "integer"
                },
                "userId": {
                    "description": "当前用户",
                    "type": "integer"
                }
            }
        },
        "models.CreateGroupReq": {
            "type": "object",
            "properties": {
                "group_name": {
                    "type": "string"
                }
            }
        },
        "models.FriendApplyResp": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "申请人头像",
                    "type": "string"
                },
                "create_at": {
                    "type": "string"
                },
                "fromId": {
                    "type": "integer"
                },
                "msg": {
                    "description": "申请附言",
                    "type": "string"
                },
                "name": {
                    "description": "申请人昵称",
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "targetId": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.FriendReq": {
            "type": "object",
            "properties": {
                "createAt": {
                    "type": "string"
                },
                "fromId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "description": "0:申请中 1:已同意 2:已拒绝 3:已读不处理",
                    "type": "integer"
                },
                "targetId": {
                    "type": "integer"
                }
            }
        },
        "models.FriendResp": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "申请人头像",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isOnline": {
                    "type": "integer"
                },
                "name": {
                    "description": "申请人昵称",
                    "type": "string"
                }
            }
        },
        "models.GroupDetailVO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                },
                "members": {
                    "description": "成员列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GroupMemberVO"
                    }
                },
                "notice": {
                    "type": "string"
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "models.GroupMemberVO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "description": "2群主 1管理员 0普通成员",
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.InviteReq": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "invited_id": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.LoginReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createAt": {
                    "type": "string"
                },
                "fromId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "media": {
                    "description": "图片，文本，音频",
                    "type": "integer"
                },
                "msgType": {
                    "description": "0 文本 1 图片  (后续可以扩展为2 音频)",
                    "type": "integer"
                },
                "targetId": {
                    "type": "integer"
                },
                "type": {
                    "description": "单聊，群聊 chat ,groupMessage,friendRequest",
                    "type": "string"
                }
            }
        },
        "models.RegisterReq": {
            "type": "object",
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.UpdateReq": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.UserRes": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
